# Generated by Django 3.1.1 on 2020-10-06 11:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201006_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='stars',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
